### ISSUE TITLE
Gran francisco makes an absurd amount of money?

### ISSUE THREAD

**Issue by thivus** [Ofaloaf/postapoc#52] opened 2015-10-09 20:24 UTC
i don't know if it's because of their simultaneous connection to the sea trade routes and the interstate trade routes, but I noticed in my game at one point early on they were making an insane 170+ gold per month, and now their descendants have 242k gold, and another descendant from the same dynasty(but is now king of cascadia because of gavelkind) have 1.1million gold

is this working as intended?

**Comment by SteelyGlint** [comment] 2015-10-09 23:43
I think there was a bug with the Pacific invasions that caused similar symptoms in version 0.6 (that should be fixed). What version are you using?

**Comment by thivus** [comment] 2015-10-10 22:01
running 0.6.1

**Comment by SteelyGlint** [comment] 2015-10-11 00:01
Do you know if there was a failed Japanese/Russian invasion that's somehow feeding them money? I would predict that to be the cause. Check if they have any Edokko/Novorusskiy courtiers, and if the invader titles of the same culture are spitting out tons of patricians.

**Comment by SteelyGlint** [comment] 2015-10-28 23:59
I wonder if this is the vanilla bug, where you get an obscene amount of money from your steward when you catch them stealing from you.

**Closed** 2016-04-20 04:10 UTC
