### ISSUE TITLE
British and Brazilian invasions are theocracies

### ISSUE THREAD

**Issue by SteelyGlint** [Ofaloaf/postapoc#75] opened 2016-03-07 20:44 UTC
Could be a consequence of changes in 2.5.1 to how the game treats landless titles? Previously they were not theocracies, but it's unclear whether it matters that they are since they're not intended for players anyway.

**Comment by kwantamphlux** [comment] 2016-04-03 01:51
This does seem to cause some adverse effects due to the way theocracies inherit. In a game I was playing, the British's second ruler was High Church because their capital was in a High Church province, and the Thelemic religion has died out completely.

**Comment by GSonderling** [comment] 2017-03-16 18:28
I might have fix for that, but I want to know for sure. Testing it now.

**Comment by GSonderling** [comment] 2017-03-16 22:03
Just submitted pull request.

**Comment by GSonderling** [comment] 2017-05-24 11:28
If the issue is solved already it might be time to close it.

**Closed** 2017-05-24 15:15 UTC
Labels: bug
