### ISSUE TITLE
blank message pop ups

### ISSUE THREAD

**Issue by lrdnelson** [Ofaloaf/postapoc#126] opened 2017-05-17 17:58 UTC
i have been trying to play but every time i start about a month in 2 blank messages pop up and pause the game, and stop me from unpausing.

**Comment by Shadeoses** [comment] 2017-05-21 12:14
Which character, what culture and religion?

**Comment by SteelyGlint** [comment] 2017-05-22 15:53
Most likely an installation problem, since I don't think this is a widespread problem.

**Comment by SteelyGlint** [comment] 2017-05-25 20:42
This is a common outcome of parse failures in event files. I am unable to reproduce the problem either with 0.9 or with the current Github version, so I'm going to close this bug report.

**Closed by SteelyGlint** 2017-05-25 20:42 UTC
